#segm_limits: {x: {min: 0.45, max: 1.1}, y: {min: -0.6, max: 0.6}, z: {min: -0.17, max: 0.2}} ## normal table
segm_limits: {x: {min: 0.5, max: 0.9}, y: {min: -0.25, max: 0.25}, z: {min: 0.02, max: 0.6}} ## red high table
